.TH MOUSE_M908 1
.SH NAME
mouse_m908 \- control Redragon gaming mice
.SH SYNOPSIS
.B mouse_m908
[\fIOPTIONS\fR]... \fB\-c\fR \fIFILE\fR
.br
.B mouse_m908
[\fIOPTIONS\fR]... \fB\-m\fR \fIFILE\fR \fB\-n\fR \fINUMBER\fR
.br
.B mouse_m908
[\fIOPTIONS\fR]... \fB\-p\fR \fINUMBER\fR
.br
.B mouse_m908
\fB\-h\fR
.SH DESCRIPTION
Change the LED lighting, the button mapping and the active profile of the Redragon M908 Impact, M709, M711 and M715 gaming mice. Support for the M709, M711 and M715 is currently experimental, see \fIREADME.md\fR for details.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print a help message.
.TP
\fB\-c\fR, \fB\-\-config\fR=\fIFILE\fR
Send the configuration from the specified .ini file to the mouse.
.TP
\fB\-m\fR, \fB\-\-macro\fR=\fIFILE\fR
Send the macros from the specified file, requires \fB\-n\fR when old macro format.
.TP
\fB\-n\fR, \fB\-\-number\fR=\fIFILE\fR
Select the macro slot to send to (1-15), requires \fB\-m\fR.
.TP
\fB\-p\fR, \fB\-\-profile\fR=\fINUMBER\fR
Set the currently active profile (1-5).
.TP
\fB\-b\fR, \fB\-\-bus\fR=\fINUMBER\fR
USB bus id, with this option the mouse gets opened by its bus id and device address instead of the VID and PID. Requires \fB\-d\fR.
.TP
\fB\-d\fR, \fB\-\-device\fR=\fINUMBER\fR
USB device address, with this option the mouse gets opened by its bus id and device address instead of the VID and PID. Requires \fB\-b\fR.
.TP
\fB\-k\fR, \fB\-\-kernel\-driver\fR
Do not attempt to detach the kernel drivers. Useful for compatibility on some systems.
.TP
\fB\-v\fR, \fB\-\-version\fR
Print version.
.TP
\fB\-R\fR, \fB\-\-read\fR=\fIFILE\fR
Read settings from the mouse and print the configuration to the specfied file. Uses stdout when \fIFILE\fR is "-".
.TP
\fB\-D\fR, \fB\-\-dump\fR=\fIFILE\fR
Read settings from the mouse and dump the raw data to the specfied file. Uses stdout when \fIFILE\fR is "-". Only useful for debugging and development.
.TP
\fB\-M\fR, \fB\-\-model\fR=\fINAME\fR
Specifies the model of the mouse (709, 711, 715, 908, 990, generic). Without this option the program attempts to detect the mouse you have connected.
.SH EXAMPLES
To send the configuration from example.ini
.PP
.nf
.RS
mouse_m908 -c example.ini
.RE
.fi
.PP
To explicitly state which mouse to open, use the \fB\-\-model\fR option, e.g. for the M709
.PP
.nf
.RS
mouse_m908 -c example_m709.ini -M 709
.RE
.fi
.PP
To send the macro from example.macro to slot 1
.PP
.nf
.RS
mouse_m908 -m example.macro -n 1
.RE
.fi
.PP
To send all macros from example.ini
.PP
.nf
.RS
mouse_m908 -m example.ini
.RE
.fi
.PP
To read and print the current config in .ini format
.PP
.nf
.RS
mouse_m908 -R -
.RE
.fi
.PP
.SH FILES
Examples and the configuration file description can be found in \fI/usr/share/doc/mouse_m908\fR, \fI/system/documentation/packages/mouse_m908\fR on Haiku.
.SH COPYRIGHT
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.
