on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  fedora-rpm-build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v2
      - name: install tools and dependencies
        run: |
          dnf install -y rpm-build findutils clang-tools-extra 'dnf-command(builddep)'
          dnf builddep -y mouse_m908.spec
      - name: build mouse_m908 rpm package
        run: |
          make -j4 rpm

  copr-build:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    container: ghcr.io/akdev1l/copr-build:latest
    steps:
      - uses: akdev1l/copr-build@main
        env:
          COPR_API_TOKEN_CONFIG: ${{ secrets.COPR_API_TOKEN_CONFIG }}
        with:
          owner: akdev
